[package]
name = "Graphics"
version = "0.1.0"
authors = ["Brian Thompson <tho17054@byui.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autopilot = "0.4.0"
glium = "0.27.0"
image = "0.23.10"